language: node_js
node_js:
  - '5'
before_deploy: "mv heroku-conf.yml config.yml"
deploy:
  provider: heroku
  api_key:
    secure: yHn1skVt8sUiQO/iyjWkr1usNQtW64wvNwuDN6CsIl6g9uqUHZikeWiVsKL7gSFcYPWBf9fyeSkOGaOIaktQhPkiTCBhAALMyyWQWiX0tTgvUNYkkVTkrlpG3jA5XfntAJQY17+MVkF67Lmmbsb0dora8l3ZLHvHBkO2NhHcq6oc2EBWjN8cLH9DkeD5ptP4enXZBNEyNxP35UhiMq/WnIjyvEH655zlA88REPE/qNqFZN7TLUovUXKYdKlyUeE0ETs0gM6q2TwGQhc/6kgEtHyAD1w6f2tZqWWR6Ch4kc7HB6IHSXzLLjua1VzIy4jGJZZ//FhrZGmmYXXGxxLO8KfCMuSMM3yEvJa4vGNuHeRpZcObl4fOW+KGw/clDg0nqTH+g5piWhd+JBzobL7zpAYkztKpUbIIBx4S1Obaha2BQLU0gQnPJIZjceRLyANsYV9p3xnoVkNeITUjq8Ps5rx7xzCxHIHJslmWd8iDg6DxZHiTpzv+1j5CkiD4GcFT5y57Am6tEG5q+nUy1Un1aFpvQt6syDOyF6rlyRDVvu6KLhAHPVKamYsXDaH5240tnN7g4zDEgJRbCKsvwneHRPyouVpTeBC37dmfQTejg4UBp87k5tZ5MVSFYLczE+ZYOH80Jb37ezGBiYZrRqxCfQKAPd91lrqtJh5eIsukMIs=
  app: feed-1
